### ISSUE TITLE
As a User I want GET version of 'find' api, so I can play with it easily

### ISSUE THREAD

**Issue by dimus** [gnames/gnfinder#107]

**Comment by nickynicolson** [comment]
I support this too - I'd like to be able to recommend the finder API to researchers manipulating data in [Open Refine](https://openrefine.org). Its too complex to integrate from this kind of tool using POST - GET would make your service much more usable.

**Comment by dimus** [comment]
I will bump the priority of this issue up, I agree, it is a valid point @nickynicolson

**Comment by dimus** [comment]
should work now with something like

https://finder.globalnames.org/api/v1/find/my%20fav%20pockemon%20is%20Bubo%20bubo

docs:

`https://apidoc.globalnames.org/gnfinder#/default/get_find__text_`
