### ISSUE TITLE
Inconsistency between v0.16.3 and v0.17.0

### ISSUE THREAD

**Issue by Adafede** [gnames/gnfinder#112]
Hi,

I read the changelogs and I know some breaking changes are expected but running my tests I observed the following:

First of all, I always use `gnfinder` with `-v`so let's check `gnverifier`:

```
echo "Malus" | bin/gnverifier -f "pretty"   
INFO[0000] Using config file: /Users/rutza/Library/Application Support/gnverifier.yaml. 
INFO[0001] Verified 1 records, 0 names/sec              
{
  "id": "8f1639fd-6e90-50c2-93f6-35ee3038638b",
  "name": "Malus",
  "matchType": "Exact",
  "bestResult": {
    "dataSourceId": 1,
    "dataSourceTitleShort": "Catalogue of Life",
    "curation": "Curated",
    "recordId": "5KQ9",
    "outlink": "https://www.catalogueoflife.org/data/taxon/5KQ9",
    "entryDate": "2021-11-20",
    "matchedName": "Malus Mill.",
    "matchedCardinality": 1,
    "matchedCanonicalSimple": "Malus",
    "matchedCanonicalFull": "Malus",
    "currentRecordId": "5KQ9",
    "currentName": "Malus Mill.",
    "currentCardinality": 1,
    "currentCanonicalSimple": "Malus",
    "currentCanonicalFull": "Malus",
    "isSynonym": false,
    "classificationPath": "Biota|Plantae|Tracheophyta|Magnoliopsida|Rosales|Rosaceae|Amygdaloideae|Malus",
    "classificationRanks": "unranked|kingdom|phylum|class|order|family|subfamily|genus",
    "classificationIds": "5T6MX|P|TP|MG|3Z6|FTK|7NDYQ|5KQ9",
    "editDistance": 0,
    "stemEditDistance": 0,
    "matchType": "Exact",
    "scoreDetails": {
      "infraSpecificRankScore": 0,
      "fuzzyLessScore": 1,
      "curatedDataScore": 1,
      "authorMatchScore": 0.2857143,
      "acceptedNameScore": 1,
      "parsingQualityScore": 1
    }
  },
  "dataSourcesNum": 25,
  "curation": "Curated"
}

# Giving a result
``` 

Now, what I had until now (and would somehow expect):

```
echo "Malus" | bin/gnfinder -v -l eng -f "pretty"   
{
  "metadata": {
    "inputFile": "STDIN",
    "nameFindingSec": 0.000042343,
    "nameVerifSec": 5.678847,
    "totalSec": 5.6788893,
    "date": "2022-01-07T09:30:59.246854+01:00",
    "gnfinderVersion": "v0.16.3",
    "withBayes": true,
    "WithBytesOffset": false,
    "withOddsAdjustment": false,
    "withVerification": true,
    "wordsAround": 0,
    "language": "eng",
    "detectLanguage": false,
    "totalWords": 1,
    "totalCandidates": 1,
    "totalNames": 1
  },
  "names": [
    {
      "cardinality": 1,
      "verbatim": "Malus",
      "name": "Malus",
      "oddsLog10": 5.065231895043268,
      "start": 0,
      "end": 5,
      "annotationNomenType": "NO_ANNOT",
      "verification": {
        "inputId": "8f1639fd-6e90-50c2-93f6-35ee3038638b",
        "input": "Malus",
        "matchType": "Exact",
        "bestResult": {
          "dataSourceId": 1,
          "dataSourceTitleShort": "Catalogue of Life",
          "curation": "Curated",
          "recordId": "5KQ9",
          "outlink": "https://www.catalogueoflife.org/data/taxon/5KQ9",
          "entryDate": "2021-11-20",
          "matchedName": "Malus Mill.",
          "matchedCardinality": 1,
          "matchedCanonicalSimple": "Malus",
          "matchedCanonicalFull": "Malus",
          "currentRecordId": "5KQ9",
          "currentName": "Malus Mill.",
          "currentCardinality": 1,
          "currentCanonicalSimple": "Malus",
          "currentCanonicalFull": "Malus",
          "isSynonym": false,
          "classificationPath": "Biota|Plantae|Tracheophyta|Magnoliopsida|Rosales|Rosaceae|Amygdaloideae|Malus",
          "classificationRanks": "unranked|kingdom|phylum|class|order|family|subfamily|genus",
          "classificationIds": "5T6MX|P|TP|MG|3Z6|FTK|7NDYQ|5KQ9",
          "editDistance": 0,
          "stemEditDistance": 0,
          "matchType": "Exact"
        },
        "dataSourcesNum": 25,
        "curation": "Curated"
      }
    }
  ]
}

# Giving a result
```

But with the new version:

```
echo "Malus" | gnfinder -v -l eng -f "pretty" 
{
  "metadata": {
    "inputFile": "STDIN",
    "nameFindingSec": 0.000048057,
    "totalSec": 0.000048057,
    "date": "2022-01-07T09:31:52.751821+01:00",
    "gnfinderVersion": "v0.17.0+",
    "withBayes": true,
    "withPositionInBytes": false,
    "withOddsAdjustment": false,
    "withVerification": true,
    "wordsAround": 0,
    "language": "eng",
    "detectLanguage": false,
    "totalWords": 1,
    "totalCandidates": 1,
    "totalNames": 0
  },
  "names": null
}

# No more result
```

I am sorry to annoy you with so many issues, your tools are wonderful and I am following their improvement with great enthusiasm! Let's be positive and grateful! 😊

**Comment by dimus** [comment]
It is actually very helpful to get fast feedback, so thank you @Adafede!

This inconsistency happened because of updated "grey" dictionary. I am trying to remove false positives that happen because quite a lot of generic names are also "normal" words. So such things like "America", "Cancer", "La", "Helena", "Acacia", "Ajax" etc go to an ambiguous dictionary, otherwise a lot of these names create false detections. I am planning to add machine learning tool that would be able to figure out if it is a scientific name or a "normal word" based on the surrounding words, but for now I only add such names to the results if they have a known species epithet next to them.

I do add new "grey" words constantly, and it looks like `Malus` got there this time, so it is not really connected to the change of output, rather to a change in dictionaries.

One way to help the problem would be to keep single "grey" genera until the last moment, and display them in the results if there are detected species of the genus in the text. In your example `Malus` would be provided if there is also `Malus viridis` in the result. This is a "cheaper" solution than machine learning and can be added relatively fast. Is it something that would help in your case?

**Comment by Adafede** [comment]
Oh, we already discussed the dictionaries, forgot it could come from there!

Yes...all those ones are challenging, I perfectly agree.

Your suggestion does not help my personal case but looks like a good first set before ML! 😊 

Maybe adding something like `--grey TRUE`, allowing single genera to be matched would be easily implementable?

**Comment by dimus** [comment]
hm, yes, I can add something like --allow-ambiguous-uninomials as another way to deal with this problem

**Comment by Adafede** [comment]
Really a detail...do not waste time with it while other appealing projects call! :)

**Comment by dimus** [comment]
Ok, I am closing this issue and opening https://github.com/gnames/gnfinder/issues/113 and https://github.com/gnames/gnfinder/issues/114

**Comment by Adafede** [comment]
Great, as always!

**Comment by dimus** [comment]
@Adafede for something completely different: 

I am trying to figure out how to make a datasets comparison tool. **If** it is something you would benefit from, the tool is at https://github.com/gnames/gndiff/releases/tag/v0.1.1 and I would love to hear your feedback. You help me a lot with your feedback and ideas!

**Comment by Adafede** [comment]
I saw you released it but had got no time to have a look at it sadly… I’ll give it a go in the coming days and let you know!
