### ISSUE TITLE
problem with some capitalized epiteths

### ISSUE THREAD

**Issue by abubelinha** [gnames/gnfinder#123]
My source text contains some botanical names where the epithets are capitalized when they refer to people's or places' names.
i.e. "_Linaria **H**aenseleri_ Bss. et Reut." or "_Euonymus **E**europaeus_ L."

Because of that, gnfinder is detecting these names as genus: "_Linaria_", "_Euonymus_"
Is there any way to improve this behaviour so it tries to lowercase the word after genus, just in case it matches some known species? (and if not, then fall back to genus)

**Comment by dimus** [comment]
yes, capitalized epithets are not supported. I tried to take them into account and they generated too many false positives

**Comment by abubelinha** [comment]
Thanks.

So I will try to lowercase myself the 1st letter after each cardinality-1
name returned, and then process the whole text again.

**Comment by dimus** [comment]
This issue might be fixed in some dinstant future when we are able to perform a second run to ehnance found generic names and detect capitalized sp. epithets.
