### ISSUE TITLE
Document false positive Euthycarcinus

### ISSUE THREAD

**Issue by Archilegt** [gnames/gnfinder#129]
There is a false positive for _Euthycarcinus_ Handlirsch, 1914 in a text dated 1911. See: https://www.biodiversitylibrary.org/page/30153565

**Comment by dimus** [comment]
Thank you @Archilegt for spotting this,

@Archilegt, @mlichtenberg, @cajunjoel this looks like another artifact from the  "before gnfinder" years. This is what gnfinder v1.0.1 got from this page:

```csv
Index,Verbatim,Name,Start,End,OddsLog10,Cardinality,AnnotNomenType,WordsBefore,WordsAfter
0,,C. solstitialis,1987,2002,7.67,2,,,
1,,Ceratopogon,1957,1968,4.65,1,,,
2,,E. duboscqi,188,199,4.28,2,,,
3,,E. murmanicum,679,692,7.06,2,,,
4,,Eleutheroschizon,12,28,4.36,1,,,
5,,Ophelia,874,881,5.04,1,,,
6,,S. sipunculi,2025,2037,5.84,2,,,
7,,Schizocystidae,909,923,5.11,1,,,
8,,Schizocystis,1225,1237,4.94,1,,,
9,,Schizocystis sipunculi,2061,2084,11.18,2,,,
10,,Scoloplos armiger,645,662,5.39,2,,,
11,,Selenidium sipunculi,2155,2176,11.58,2,,,
```

**Comment by mlichtenberg** [comment]
Yes, it was a leftover from the TaxonFinder-based version of GNRD.  I have disassociated that name from the page.
