### ISSUE TITLE
README.md - make public API endpoint more obvious

### ISSUE THREAD

**Issue by nickynicolson** [gnames/gnfinder#135]
There is a useful public API endpoint available via https://finder.globalnames.org/ but this is not easily found in the README for this repo - could it be made more prominent please?
Personally I would put "Use via a REST API" above "Install as a command line app" - as a potential user will first want to try the functionality before investing the time in a local installation.

**Comment by dimus** [comment]
@nickynicolson, thank you, makes sense. I guess README follows historical appearance of different interfaces, with CLI happening before others
