### ISSUE TITLE
name change in the 1.1.0 release

### ISSUE THREAD

**Issue by Adafede** [gnames/gnfinder#137]
Hi @dimus, as always thank you for your hard work!

The name of the unziped archives of 1.1.0 was change to "out", was it on purpose? Just to know if I need to change my pattern 😊

**Comment by dimus** [comment]
oups, no, my bad, I will change it back! thank you for letting me know

**Comment by dimus** [comment]
@Adafede, I changed the binary archives, all should be back to the way it was for this and next releses.

**Comment by Adafede** [comment]
Marvelous, thank you very much!
