### ISSUE TITLE
As a developer I would like to see `sp.nov.` without not return NO_ANNOT

### ISSUE THREAD

**Issue by mjy** [gnames/gnfinder#140]
Probably an issue with token handling requiring spaces.  If we can't handle here I'll pre-propcess the text.

```ruby
3.2.1 :022 > t = 'Turripria woldai sp.nov'
 => "Turripria woldai sp.nov" 
3.2.1 :023 > t = 'Turripria woldai sp.nov'
 => "Turripria woldai sp.nov" 
3.2.1 :024 > r = Vendor::Gnfinder.result(t, project_id: 13)
 => 
#<Vendor::Gnfinder::Result:0x0000000117aedae0
... 
3.2.1 :025 > r.names.first.found.annotation_nomen_type
 => "NO_ANNOT" 
 ```

**Comment by dimus** [comment]
makes sense, I'll think how to deal with this.

**Comment by mjy** [comment]
Other combinations that seems to not be detecting:

* `Coccidencyrtus pomadus sp. nov..\n` (could be wrong on this)

**Comment by mjy** [comment]
Other combinations that succeed, somewhat unexpectedly:

*  `Coccidencyrtus pomadus sp. nov...`
* `*#Cheiloneurus nasica sp. nov..,`

**Comment by dimus** [comment]
> Other combinations that seems to not be detecting:
> 
> * `Coccidencyrtus pomadus sp. nov..\n` (could be wrong on this)

I think this is part of #143
