### ISSUE TITLE
As a User I want to have an option to generate output with all candidate words, not just names

### ISSUE THREAD

**Issue by dimus** [gnames/gnfinder#2]
Such output would allow to use the text for tagging in a more efficient way.

**Comment by mjy** [comment]
All candidate words... also with their probability of being a name?

**Comment by dimus** [comment]
I understood that it would be a huge toll on storage, so I scrapped it for now :-/
During the name-finding process while I still have all the tokens in memory I can calculate probabilities dynamically, and these will be just one int field per page.
