### ISSUE TITLE
MatchType: JSON vs protob

### ISSUE THREAD

**Issue by LocoDelAssembly** [gnames/gnfinder#47]
There seems to be al little difference between JSON and protobuf responses. In particular, there is a distinction between ExactMatch and variations of CanonicalMatch. However in protob responses canonical is no longer reflected and even two distinct cases are translated to the same type in [getMatchType](https://github.com/gnames/gnfinder/blob/f8a499287b88cd46073f57380f1e955e1bca8d5b/grpc/grpc.go#L193)

An earlier version of the code (which I failed to determine the exact moment this changed), used to be this: 
```go
func getMatchType(match string) protob.MatchType {
	switch match {
	case "ExactMatch":
		return protob.MatchType_EXACT
	case "ExactCanonicalMatch":
		return protob.MatchType_CANONICAL_EXACT
	case "FuzzyCanonicalMatch":
		return protob.MatchType_CANONICAL_FUZZY
	case "ExactPartialMatch":
		return protob.MatchType_PARTIAL_EXACT
	case "FuzzyPartialMatch":
		return protob.MatchType_PARTIAL_FUZZY
	}
	return protob.MatchType_NONE
}
```

Is the current implementation OK?

**Comment by dimus** [comment]
After discussion we decided to go with protobuf/gRPC to communicate with gnfinder from Ruby.
Also #49 introduced some cleaning up in JSON and protobuf outputs.
