### ISSUE TITLE
As a User I want an improvement in protobuf output

### ISSUE THREAD

**Issue by dimus** [gnames/gnfinder#49]
Problems:
1. type fields returns a string, and the strings are cryptic. For example it is hard to understand what is ProbablyBinomial, or Binomial(nlp).
Solution: break it into 2 fields:
* cardinality: 0-3 (0 is no match, 1 uninonial, 2 binomial, 3 trinomial)
* method: enum array with following possible results: [HEURISTIC] or [HEURISTIC, BAYES]

2. Add more information to resolution data with fields:
matchedCardinality
matchedCanonicalSimple
matchedCanonicalFull
currentNameCardinality
currentNameCanonicalSimple
currentNameCanonicalFull

**Comment by Adafede** [comment]
Hi, 

Sorry to bother you (again). It is a really nice push you did but it seems like the outputs of Linux and OSX are not the same now... Linux outputs seem new (matchedCanonical***Simple*** et cætera) but OSX remained the same.
We just saw it with @oolonek comparing our results.

**Comment by oolonek** [comment]
Small typos differences also for example:

Linux:
`names.verification.bestResult.dataSourceTitle`

MacOS:
`names.verification.BestResult.dataSourceTitle`

**Comment by Adafede** [comment]
my deepest apologies...messed up with my environments...I wasn't using last version...you can ignore this whole thing.

**Comment by oolonek** [comment]
> Small typos differences also for example:
> 
> Linux:
> `names.verification.bestResult.dataSourceTitle`
> 
> MacOS:
> `names.verification.BestResult.dataSourceTitle`

The above comment is still valid.
Same version (version: v0.11.0) on two different platforms (Debian 9 and MacOS X)

**Comment by dimus** [comment]
I am running v0.11.0 on a mac terminal with input "Plantago major" and getting the following:

```json
{
  "metadata": {
    "date": "2020-05-08T13:56:37.679789-05:00",
    "gnfinderVersion": "v0.11.0",
    "withBayes": true,
    "tokensAround": 0,
    "language": "eng",
    "detectLanguage": false,
    "totalWords": 2,
    "totalCandidates": 1,
    "totalNames": 1
  },
  "names": [
    {
      "cardinality": 2,
      "verbatim": "Plantago major",
      "name": "Plantago major",
      "odds": 21035.578253671665,
      "start": 0,
      "end": 14,
      "annotationNomenType": "NO_ANNOT",
      "annotation": "",
      "verification": {
        "bestResult": {
          "dataSourceId": 1,
          "dataSourceTitle": "Catalogue of Life",
          "taxonId": "53918411",
          "matchedName": "Plantago major Elliott",
          "matchedCardinality": 2,
          "matchedCanonicalSimple": "Plantago major",
          "matchedCanonicalFull": "Plantago major",
          "currentName": "Plantago rugelii Decne.",
          "currentCardinality": 2,
          "currentCanonicalSimple": "Plantago rugelii",
          "currentCanonicalFull": "Plantago rugelii",
          "isSynonym": true,
          "classificationPath": "Plantae|Tracheophyta|Magnoliopsida|Lamiales|Plantaginaceae|Plantago|Plantago rugelii",
          "classificationRank": "kingdom|phylum|class|order|family|genus|species",
          "classificationIds": "54767868|54767869|54767870|54768638|54773450|54986330|53578383",
          "matchType": "ExactCanonicalMatch"
        },
        "dataSourcesNum": 29,
        "dataSourceQuality": "HasCuratedSources",
        "retries": 1
      }
    }
  ]
}
```

try ``gnfinder -v`` looks like you are still running an older version

**Comment by oolonek** [comment]
@dimus Correct ... I was actually checking an old input also ! :/ 
My bad ...
