### ISSUE TITLE
Improve dictionaries

### ISSUE THREAD

**Issue by dimus** [gnames/gnfinder#51]
In #43 @Adafede wrote:
Hi,

Wonderful for the doc! Thank you for all your hard work and the nice last versions you developed. Now that I am able to build from scratch I had the opportunity to have a more careful look at the dictionaries and related files.

I therefore have a question:
Is there a precise reason why you chose to put piper in your black uninomials dictionary?

I am asking you this because I am interested in this species and can not afford loosing it during text recognition. Therefore, since I was not able to build from scratch till now I used the R taxize package which, in a certain way, allows to find more results than the ones obtained with GNFinder, although they use your tool! I think this is because they removed some entries of your black dictionaries but I'm not sure about it. @sckott

I could build my own version on my side and modify accordingly (commenting piper for example) but I think it is more useful to discuss this point publicly and maybe find common solutions in order to avoid everyone having its own version.

If you are interested in it, I already retrieved manually some problematic entries that are found in some biological databases and lead to aberrant results, such as (in alphabetical order):

japanese yew (Taxus cuspidata)
anaerobic (is already in your list, but probably taxize ignores it)
candidatus (same as anaerobic)
chinensis
green (same as anaerobic)
megaleia
ootheca
peripatoides
red (same as anaerobic)
sinensis
tasmanian
uncultured

Many thanks again

**Comment by dimus** [comment]
@Adafede, thank you for your kind words, the dictionaries is a perpetual work in progress, so thank you for your help!

I do agree that it is better to fix problems that are of common interest in the 'official' gnfinder, so all users can benefit from the improvements.

As you can imagine I did not start by looking at every word to decide where to place it and used algorithms, and algorithms make mistakes. Therefore user feedback is very important to straighten out the remaining kinks.

Lets go through your post:

`piper` - is it a vernacular, or a part of a Sci name?

@sckott, are you using GNRD in taxize? Hm I wonder why results differ, as
I did switch GNRD to gnfinder as well. @Adafede, would be interesting to find what gnfinder is missing for you in comparison to older implementation.
As I understand all of the following "names" are black dictionary candidates. I will check them one by one against names DB and add them accordingly.

```
japanese yew (Taxus cuspidata)
anaerobic (is already in your list, but probably taxize ignores it)
candidatus (same as anaerobic)
chinensis
green (same as anaerobic)
megaleia
ootheca
peripatoides
red (same as anaerobic)
sinensis
tasmanian
uncultured
```

**Comment by Adafede** [comment]
It is scientific, it is a very important genus! (>2000 species)

[Piper](http://www.catalogueoflife.org/annual-checklist/2019/browse/tree/id/3097232b9c81b159e44ed1726089a93e)

That is the reason why I would love it to be taken out of the black list...

for the entries I mentioned, yes, they are candidates...

chinensis/megaleia/sinensis/peripatoides are [specific names](https://en.wikipedia.org/wiki/Specific_name_(zoology)) which are sadly sometimes recognized as [generic names](https://en.wikipedia.org/wiki/Genus#Generic_name) in some DBs.

the other adjectives are quite obvious I think. I also have some common names to ignore if you want them (I did not check yet all the overlap with yours).

**Comment by dimus** [comment]
I would appreciate very much to learn how to improve black grey and white dictionaries. If you can prepare a list of what you found as a **separate** ticket (so we keep tickets "closeable"). If you can also mark them into some categories, would be very helpful, something like:

piper : black uni -> grey uni (to indicate movement from black to grey)
laptop :  black uni, black sp (to indicate addition)

I will still check them with the name database

Would be great to develop some format for changes in dictionaries, so people can use it to submit large number of corrections in unambiguous and ergonomic way.

> chinensis/megaleia/sinensis/peripatoides are specific names which are sadly sometimes recognized as generic names in some DBs.

http://index.globalnames.org/search?q=gen:chinensis&db=&bo=false

http://index.globalnames.org/search?q=gen:megaleia&db=&bo=false

http://index.globalnames.org/search?q=gen:sinensis&db=&bo=false

http://index.globalnames.org/search?q=gen:peripatoides&db=&bo=false

Looks like they are. It whould not matter in most cases, as gnfinder assumes that species epithets are not capitalized.

(For old literature with capitalized species we would need to develop some smart trickery in the future)

There is also a question on the algorithm to develop generic dictionaries. 
There is [IRMNG] (https://irmng.org/export/) which is probably the most advanced list of generic names.
There is a list of all generic names from index.globalnames.org
There is a list of all generic names from databases that are considered to be manually curated.

**Comment by Adafede** [comment]
To be honest, all those things are quite new to me so no idea how to do it...but you are right, would be best to find an efficient way to do it!

For the mentioned species/genera...my bad I know multiple species where those strings are specific names and not generic. Must be indeed a capitalization problem.

I'll try to work on the lists and come back to you as soon as I find a clever way to do it (or if you find one in the meantime)

**Comment by dimus** [comment]
Not that clever is OK, cleverness can be added incrementally :D

**Comment by sckott** [comment]
Yes, we have a function in taxize, see https://docs.ropensci.org/taxize/reference/scrapenames.html  I don't have a sense as to why things would differ. The parameters defaults should match the defaults you have set in the API

**Comment by dimus** [comment]
> Yes, we have a function in taxize, see https://docs.ropensci.org/taxize/reference/scrapenames.html I don't have a sense as to why things would differ. The parameters defaults should match the defaults you have set in the API

@sckott do you have GNRD server running somewhere? https://gnrd.globalnames.org changed its API a bit and runs only gnfinder now. Would be good to switch to that API, as it is significantly faster and will be improved further. Older API is still available at https://gnrdbhl.globalnames.org

**Comment by sckott** [comment]
no, i don't run gnrd as a server. i only use your web API for gnrd. we use the URL http://gnrd.globalnames.org/name_finder.json - is that the new one?

**Comment by dimus** [comment]
yes here is the description http://gnrd.globalnames.org/api

**Comment by sckott** [comment]
thanks

**Comment by dimus** [comment]
Removed piper from black, and added some of the black ones @Adafede  suggested. A few of them like chinensis to exist in db as genus or species, so they are not added. There is a new dictionary generator now https://github.com/gnames/gndict

**Comment by Adafede** [comment]
Thank you very much!

I'm still working on ways to have more entries to give you but it requires some time... do you plan a new version soon or do I compile it from the actual git?

**Comment by dimus** [comment]
@Adafede I am not going to make a new release just yet, because I am in the process of updating my master dictionary at index.globalnames.org (updating major data sources and adding quite a few new smaller sources). These changes will bring quitie a few new names hopefully that will propagate into dictionary, so I am going to postpone release until all these updates are in (~2-3 weeks from now). So go ahead and compile if yourself.

**Comment by dimus** [comment]
v0.11.1 is out with updated dictionaries

**Comment by Adafede** [comment]
just saw it, absolutely great thank you!
