### ISSUE TITLE
Issue using offsetStart and offsetEnd

### ISSUE THREAD

**Issue by mwiecksosa** [gnames/gnfinder#57]
Hi, how would I go about using the offsetStart and offsetEnd returned so that I can easily find the exact location of words of the recognized species in the text? Thanks for any help you could give @dimus

**Comment by dimus** [comment]
@mwiecksosa, offsetStart is the number of UTF-8 characters from the start of the input text to the start of a detected name-string, offsetEnd is the number to the end of the name-string.

**Comment by dimus** [comment]
no further feedbacks, so looks like we can close this issue.

**Comment by mwiecksosa** [comment]
Hmm, I'm still trying to figure it out @dimus . I was reading the original file with UTF-8 characters in Python and am trying to look for the recognized words using file.seek(offsetStart) with the Pyton seek() method and the line = file.read(offsetEnd-offsetStart) with the read() method and still no luck.

**Comment by dimus** [comment]
Python is not a language I know that well, but here is an example:

```python
#!/usr/bin/env  python

import subprocess
import json

text = "Паук Pardosa moesta (spider)"
command = "echo '{text}' | gnfinder find".format(text = text)

output=subprocess.check_output(command, shell=True)
name = json.loads(output)["names"][0]
start = name["start"]
end = name["end"]
print(text[start:end])
```

It assumes you have gnfinder installed in your PATH. Python 3 seem to respect UTF-8 encoding by default.

**Comment by mwiecksosa** [comment]
Got it! Issue resolved. One should read the entire text as a UTF-8 string. In Python, for a .txt file, it's as simple as this:
```python
import io
f = io.open(pathToFile+fileName, mode="r", encoding="utf-8")
extractedText = text[offsetStart:offsetEnd] # where offsetStart and offsetEnd are from the returned json for that recognized species name
```
