### ISSUE TITLE
Getting Started with OSX

### ISSUE THREAD

**Issue by poldham** [gnames/gnfinder#9]
Hi Dmitry, Great to see this and many thanks. I have been trying to get the app up and running in both Mac OSX and Windows but am not getting past first base. In Mac OSX with gnfinder in the applications folder it launches but then simply shows a start up screen. On windows I seem to need the path to launch but am not getting past first base with that either. When you have some time would you mind jotting down some notes in the read me on how to actually get started - for complete idiots like me. Great to see this turning in to a user application and I need to follow up with you by email on something else. Best, Paul

**Comment by dimus** [comment]
I guess I need to add an info how to add gnfinder to path on Windows, OS X/Linux

**Comment by poldham** [comment]
Many thanks Dmitry. I will take a look at that and get back to you. I think when there is some time some more instructions to help folks get going will be really helpful. Best, Paul

**Comment by dimus** [comment]
@poldham , I put together instructions how to set gnfinder on Windows and Mac. If you feel more instructions are needed, add a description of what would you like to see in a comment and reopen this ticket
