### ISSUE TITLE
`-u` and `-w` conflict

### ISSUE THREAD

**Issue by ka7eh** [gnames/gnfinder#97]
I'm not sure if it's intentional or a bug (I didn't notice anything in the docs), but using `-u` and `-w` flags together ignores the latter flag and doesn't include the words before and after in the results.

**Comment by dimus** [comment]
It is intentional. `-u` returns *unique* set of names, it means a name can be potentially many times in a text, so 
`-w` flag looses sense in such case.  Adding this to documentation.
